'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50215.44
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
<Assembly: Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope := "member", Target := "DocumentView.Settings.get_Default():DocumentView.Settings")>

Namespace My


	<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
	Friend NotInheritable Partial Class Settings : Inherits Global.System.Configuration.ApplicationSettingsBase

		Private Shared defaultInstance As Settings = New Settings()

		Public Shared ReadOnly Property [Default]() As Settings
			Get
				Return defaultInstance
			End Get
		End Property
	End Class
End Namespace
